### ISSUE TITLE
Provide quasi-quoters

### ISSUE THREAD

**Issue by hasufell** [nikita-volkov/postgresql-syntax#4]
I'm using this library to transform and modify user-input SQL, so I pass around a lot of AST objects. Some of these are huge and static, so I don't want to copy-paste the entire thing, nor do I want to run the parser at runtime.

It's probably straight-forward to implement, I might give it a shot if this is deemed interesting.

**Comment by mgajda** [comment]
@hasufell @nikita-volkov Is there a viable alternative to this PR?

**Comment by nikita-volkov** [comment]
See https://github.com/nikita-volkov/postgresql-syntax/pull/5#issuecomment-1445216021
